export { default as Whatsapp } from "@/public/svg/icons/whatsapp.svg";
export { default as Arrow } from "@/public/svg/icons/AltArrow Up.svg";
export { default as World } from "@/public/svg/icons/ChatLine.svg";
export { default as About } from "@/public/svg/icons/about.svg";
export { default as Users } from "@/public/svg/icons/Users.svg";
export { default as ShieldCheck } from "@/public/svg/icons/ShieldCheck.svg";
export { default as Send } from "@/public/svg/icons/Plain.svg";
export { default as Gear } from "@/public/svg/icons/Gear.svg";
export { default as StarsYellow } from "@/public/svg/icons/SubContainer.svg";
export { default as ChickRight } from "@/public/svg/icons/right.svg";
export { default as Pulse } from "@/public/svg/icons/pluse.svg";
export { default as Negative } from "@/public/svg/icons/negative.svg";
export { default as Phone } from "@/public/svg/icons/Phone.svg";
export { default as Email } from "@/public/svg/icons/email.svg";
export { default as User } from "@/public/svg/icons/User.svg";
export { default as ChatLine } from "@/public/svg/icons/ChatLine.svg";
export { default as Location } from "@/public/svg/icons/location.svg";
export { default as Telegram } from "@/public/svg/icons/Telegram.svg";
export { default as Facebook } from "@/public/svg/icons/facebook.svg";
export { default as LinkedIN } from "@/public/svg/icons/LinkedIn.svg";
export { default as Twitter } from "@/public/svg/icons/twitter.svg";
export { default as Instagram } from "@/public/svg/icons/Instagram.svg";
export { default as FooterLogo } from "@/public/svg/icons/footer.svg";
export { default as Search } from "@/public/svg/icons/search-normal.svg";
export { default as ArrowBack } from "@/public/svg/icons/Vector 2.svg";
export { default as Amazon } from "@/public/svg/icons/amazon.svg";
export { default as Noon } from "@/public/svg/icons/noon.svg";
export { default as Pin } from "@/public/svg/icons/pin.svg";
export { default as Menu } from "@/public/svg/icons/menu.svg";
export { default as Whatsappside } from "@/public/svg/icons/Whatsappside.svg";
export { default as Telegramside } from "@/public/svg/icons/Telegramside.svg";
export { default as Messenger } from "@/public/svg/icons/Messenger.svg";
export { default as Phoneside } from "@/public/svg/icons/phoneside.svg";
export { default as BoxMinimalistic } from "@/public/svg/icons/Box Minimalistic.svg";
export { default as ClockCircle } from "@/public/svg/icons/Clock Circle.svg";
export { default as PaginationArrow } from "@/public/svg/icons/Alt Arrow Left.svg";
export { default as YellowStar } from "@/public/svg/icons/YellowStar.svg";
export { default as FolderWithFiles } from "@/public/svg/icons/Folder With Files.svg";
export { default as TickCircle } from "@/public/svg/icons/tick-circle.svg";
export { default as Image461TickCircle } from "@/public/svg/icons/image-46 1.svg";
export { default as WatsappWhite } from "@/public/svg/icons/WatsappWhite.svg";
export { default as Radar3 } from "@/public/svg/icons/Radar3.svg";
export { default as CupFirst } from "@/public/svg/icons/CupFirst.svg";
export { default as StarsMinimalistic } from "@/public/svg/icons/StarsMinimalistic.svg";
export { default as What } from "@/public/svg/icons/What.svg";
export { default as InfoSquare } from "@/public/svg/icons/InfoSquare.svg";
export { default as BoltCircle } from "@/public/svg/icons/BoltCircle.svg";
export { default as DocumentText } from "@/public/svg/icons/DocumentText.svg";
export { default as FileText } from "@/public/svg/icons/FileText.svg";
export { default as DownloadMinimalistic } from "@/public/svg/icons/DownloadMinimalistic.svg";
export { default as StarsMinimalistic2 } from "@/public/svg/icons/StarsMinimalistic2.svg";
export {default as ArrowLeft} from "@/public/svg/icons/ArrowLeft.svg"